version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # Use host network mode to access host applications
    # network_mode: host
    networks:
      - default
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ceomis
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"
    networks:
      - default

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "redis"]
    volumes:
      - redis_data:/usr/local/etc/redis
    ports:
      - "6379:6379"

  garrage:
    image: dxflrs/garage:v2.0.0
    restart: unless-stopped
    ports:
      - "3900:3900"  # S3 API
      - "3901:3901"  # RPC (needed for admin commands)
      - "3902:3902"
      # - "3903:3903"
    volumes:
      - garage_data:/var/lib/garage
      - ./../server/garage-config/garage.toml:/etc/garage.toml
    networks:
      - default

  # garage-webui:
  #   image: khairul169/garage-webui:latest
  #   restart: unless-stopped
  #   ports:
  #     - "3909:3909"  # Web UI
  #   environment:
  #     S3_REGION: "garage"
  #     API_BASE_URL: "http://garrage:3903/v2"
  #     API_ADMIN_KEY: "F876F9A2E9BA1DE148E55D4D12A8F"
  #     S3_ENDPOINT_URL: "http://garrage:3900"
  #     AUTH_USER_PASS: "admin:password123"
  #   volumes:
  #     - ./garage-config/garage.toml:/etc/garage.toml:ro
  #   depends_on:
  #     - garrage
  #   networks:
  #     - default


volumes:
  postgres_data:
  redis_data:
  garage_data:

networks:
  default:
    driver: bridge
